routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::prefix('administration')->group(function () {
    /*
    |--------------------------------------------------------------------------
    | Permission Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::resource('permissions', 'Admin\PermissionsController');

    /*
    |--------------------------------------------------------------------------
    | Roles Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::resource('roles', 'Admin\RolesController');

    /*
    |--------------------------------------------------------------------------
    | Users Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::post('users/admin/store', ['as' => 'users.admin.store', 'uses' => 'Admin\UsersController@saveAdminUser']);
    Route::get('users/search/{idnum}', 'Admin\UsersController@searchClient');
    Route::resource('users', 'Admin\UsersController');

    /*
    |--------------------------------------------------------------------------
    | Login Routes | Sentinel Implementation
    |--------------------------------------------------------------------------
    */
    Route::get('login', ['as' => 'admin.login.page', 'uses' => 'Auth\LoginController@adminLoginPage']);
    Route::post('login', ['as' => 'login', 'uses' => 'Auth\LoginController@loginAttempt']);

    /*
    |--------------------------------------------------------------------------
    | Categories Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('categories', 'Admin\CategoriesController');

    /*
    |--------------------------------------------------------------------------
    | SubCategories Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('subcategories', 'Admin\SubCategoriesController');

    /*
    |--------------------------------------------------------------------------
    | Products Routes
    |--------------------------------------------------------------------------
    */
    Route::post('products/delete_image', 'Admin\ProductsController@destroyImage');
    Route::get("products/single/{id}", ['as' => 'products.single', 'uses' => 'Admin\ProductsController@getSingleProduct']);
    Route::delete('products/complex/remove/{complex_id}/{product_id}', ['as' => 'products.complex.remove',
        'uses' => 'Admin\ProductsController@removeComplex']);
    Route::resource('products', 'Admin\ProductsController');

    /*
    |--------------------------------------------------------------------------
    | Purchases Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('purchases', 'Admin\PurchasesController');

   /*
   |--------------------------------------------------------------------------
   | Providers Routes
   |--------------------------------------------------------------------------
   */
    Route::resource('providers', 'Admin\ProvidersController');

    /*
    |--------------------------------------------------------------------------
    | Sales Routes
    |--------------------------------------------------------------------------
    */
    Route::get('sales/confirm/deposit/{id}', ['as' => 'sales.confirm.deposits', 'uses' => 'Admin\SalesController@acceptDepositOrder']);
    Route::get('sales/cancel/confirm/{id}', ['as' => 'sales.confirm.cancel', 'uses' => 'Admin\SalesController@cancelConfirmOrder']);
    Route::get('sales/confirm/{id}', ['as' => 'sales.confirm', 'uses' => 'Admin\SalesController@confirmOrder']);
    Route::post('sales/delivery/', 'Admin\SalesController@deliveryCost');
    Route::get('sales/cancel/{id}', ['as' => 'sales.cancel', 'uses' => 'Admin\SalesController@cancelOrder']);
    Route::resource('sales', 'Admin\SalesController');

    /*
    |--------------------------------------------------------------------------
    | Brands Routes
    |--------------------------------------------------------------------------
    */
    Route::get('clients/search/{id}', 'Admin\CallClientsController@searchClient');
    Route::post('clients/add_sales', 'Admin\CallClientsController@addNewClientsForSale');
    Route::resource('clients', 'Admin\CallClientsController');

    /*
    |--------------------------------------------------------------------------
    | Reports Routes
    |--------------------------------------------------------------------------
    */
    Route::get('reports/utilities/monthly', ['as' => 'reports.utilities.monthly', 'uses' => 'Admin\ReportsController@monthlyUtilitiesReports']);
    Route::get('reports/utilities', ['as' => 'reports.utilities', 'uses' => 'Admin\ReportsController@utilitiesReports']);
    Route::get('reports/aex/get_delivery/{id}', ['as' => 'reports.aex.get_delivery', 'uses' => 'Admin\ReportsController@collectAexPayments']);
    Route::get('reports/aex/pay_collect/{id}', ['as' => 'reports.aex.pay_collect', 'uses' => 'Admin\ReportsController@payAexCollect']);
    Route::get('reports/aex', ['as' => 'reports.aex', 'uses' => 'Admin\ReportsController@aexReports']);
    Route::get('reports/stock', ['as' => 'reports.stock', 'uses' => 'Admin\ReportsController@generalStock']);
    Route::get('reports/sales', ['as' => 'reports.sales', 'uses' => 'Admin\ReportsController@sales']);
    Route::resource('reports', 'Admin\ReportsController');

    /*
   |--------------------------------------------------------------------------
   | Brands Routes
   |--------------------------------------------------------------------------
   */
    Route::resource('brands', 'Admin\BrandsController');

    /*
    |--------------------------------------------------------------------------
    | Departments Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('departments', 'Admin\DepartmentsController');

    /*
    |--------------------------------------------------------------------------
    | Cities Routes
    |--------------------------------------------------------------------------
    */
    Route::post('cities/add_sales', 'Admin\CitiesController@newCityBySell');
    Route::resource('departments/{department_id}/cities', 'Admin\CitiesController');

    /*
    |--------------------------------------------------------------------------
    | Admin Home Routes
    |--------------------------------------------------------------------------
    */
    Route::get('/', ['as' => 'admin.index', 'uses' => 'Admin\AdminHomeController@index']);

    /*
    |--------------------------------------------------------------------------
    | Casual Clients Routes
    |--------------------------------------------------------------------------
    */
    Route::resource('casual_clients', 'Admin\CasualClientsController');

});

/*
|--------------------------------------------------------------------------
| Login & Activation Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::get('register', ['as' => 'front.register.show', 'uses' => 'Front\Auth\RegisterController@showRegisterPage']);
Route::post('register', ['as' => 'front.register.do', 'uses' => 'Front\Auth\RegisterController@doFrontRegister']);
Route::get('register/activate/{id}/{code}', ['as' => 'front.users.activate', 'uses' => 'Front\Auth\RegisterController@activateFrontUser']);
Route::get('login', ['as' => 'login.page', 'uses' => 'Auth\LoginController@loginPage']);
Route::post('login', ['as' => 'login.do', 'uses' => 'Auth\LoginController@loginAttempt']);
Route::get('logout', ['as' => 'logout', 'uses' => 'Auth\LoginController@logout']);
Route::get('recovery', ['as' => 'show.recovery.password', 'uses' => 'Auth\LoginController@showResetPasswordPage']);
Route::post('recovery', ['as' => 'do.recovery.password', 'uses' => 'Auth\LoginController@resetPasswordRequest']);
Route::get('restore/{id}/{code}', ['as' => 'reset.password.page', 'uses' => 'Auth\LoginController@resetPasswordPage']);
Route::post('restore', ['as' => 'reset.password.do', 'uses' => 'Auth\LoginController@resetPassword']);


/*
|--------------------------------------------------------------------------
| Login & Activation Routes | Socialite Implementation
|--------------------------------------------------------------------------
*/
Route::get('login/facebook', ['as' => 'login.facebook', 'uses' => 'Front\FacebookController@redirectToFacebook']);
Route::get('login/facebook/callback', ['as' => 'login.facebook.callback', 'uses' => 'Front\FacebookController@handleFacebookCallback']);

/*
|--------------------------------------------------------------------------
| Front User Routes | Sentinel Implementation
|--------------------------------------------------------------------------
*/
Route::get("purchases/{id}/deposit", ['as' => 'orders.pre.deposit', 'uses' => 'Front\OrdersController@preFinishPurchase']);
Route::get('pending/{id}', ['as' => 'front.users.pending', 'uses' => 'Admin\UsersController@pendingPayments']);
Route::get('purchases/{header_id}/tracking', ['as' => 'front.users.purchases.tracking', 'uses' => 'Admin\UsersController@myPurchasesTracking']);
Route::post('purchases/{id}/upload', ['as' => 'front.users.purchases.upload', 'uses' => 'Admin\UsersController@uploadPurchasePicture']);

resources/views/administration/clients/edit.blade.php
@extends('administration.templates.layout') 
@section('content')
<!-- #END# Vertical Layout -->
<!-- Vertical Layout | With Floating Label -->
{!! Form::model($client, ['route' => ['clients.update', $client->id], 'method' => 'patch']) !!}

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Editar Cliente Casual {{--
                    <small>With floating label</small>--}}
                </h2>
            </div>
            <div class="body">
    @include('administration.clients.partials.fields')
            </div>
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Dirección {{--
                    <small>With floating label</small>--}}
                </h2>
            </div>
            <div class="body">
                <div class="form-group form-float">
                    <div class="form-line">
                        {{ Form::text('address', isset($client->addresses[0]->address) ? $client->addresses[0]->address : null, ['class' => 'form-control'])
                        }}
                        <label class="form-label">Calle 1</label>
                    </div>
                </div>

                <div class="form-group form-float">
                    <div class="form-line">
                        {{ Form::text('address2', isset($client->addresses[0]->address2) ? $client->addresses[0]->address2 : null, ['class' => 'form-control'])
                        }}
                        <label class="form-label">Calle2</label>
                    </div>
                </div>

                <div class="form-group form-float">
                    <div class="form-line">
                        {{ Form::text('number', isset($client->addresses[0]->number) ? $client->addresses[0]->number : null, ['class' => 'form-control'])
                        }}
                        <label class="form-label">Numero de casa</label>
                    </div>
                </div>
                <div class="form-group form-float">
                    <div class="form-line">
                        {{ Form::text('telephone', isset($client->addresses[0]->telephone) ? $client->addresses[0]->telephone : null, ['class' => 'form-control'])
                        }}
                        <label class="form-label">Telefono</label>
                    </div>
                </div>
                <div class="form-line">
                    <label id="brand_id">Ciudad</label> {!! Form::select('city_id' , $cities , isset($client->addresses[0]->city_id)
                    ? $client->addresses[0]->city_id : null, ['class' => 'form-control show-tick', 'required' => 'required'])
                    !!}
                </div>
                <button type="submit" class="btn btn-primary m-t-15 waves-effect">Guardar</button>

            </div>
        </div>
    </div>
</div>
{{ Form::close() }}

<!-- Vertical Layout | With Floating Label -->
@endsection
 
@section('css')
<!-- Bootstrap Material Datetime Picker Css -->
<link href="{{ '/admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' }}" rel="stylesheet"
/>

<!-- Wait Me Css -->
<link href="{{ '/admin/plugins/waitme/waitMe.css' }}" rel="stylesheet" />

<!-- Bootstrap Select Css -->
<link href="{{ '/admin/plugins/bootstrap-select/css/bootstrap-select.css' }}" rel="stylesheet" />
@endsection
 
@section('js')
<!-- Moment Plugin Js -->
<script src="{{ '/admin/plugins/momentjs/moment.js' }}"></script>
<!-- Bootstrap Material Datetime Picker Plugin Js -->
<script src="{{ '/admin/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' }}"></script>

<script src="{{ '/admin/js/pages/forms/basic-form-elements.js' }}"></script>
@endsection

resources/views/administration/clients/index.blade.php
@extends('administration.templates.layout') 
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Clientes Casuales
                    <small>Filtros de Busqueda</small>
                </h2>
            </div>
            <div class="body">
                <form action="{{ route('casual_clients.index') }}">
                    <div class="row">
                        <div class="col-lg-2">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    {!! Form::text('date_start', null, ['class' => 'datepicker form-control', 'id' => 'description']) !!}
                                    <label class="form-label">Desde</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    {!! Form::text('date_end', null, ['class' => 'datepicker form-control', 'id' => 'description']) !!}
                                    <label class="form-label">Hasta</label>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-2">
                            <div class="form-group form-float">
                                <div class="form-line">
                                    {!! Form::text('description', null, ['class' => 'form-control', 'id' => 'description']) !!}
                                    <label class="form-label">Descripción</label>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-lg-4">
                            <input type="hidden" name="q" value="q">
                            <button type="submit" class="btn btn-info">Filtrar</button> {{--
                            <button class="btn btn-success" name="download" value="xls">Excel</button>--}}
                            <a href="{{ route('casual_clients.index') }}" class="btn btn-warning">Ver Todos</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nombre</th>
                            <th>Cedula</th>
                            <th>Teléfono</th>
                            <th>Creado</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($clients as $c)
                        <tr class="even pointer" data-id="{{ $c->id }}">
                            <th scope="row">{{ $c->id }}</th>
                            <td>{{ $c->description }}</td>
                            <td>{{ $c->idnum }}</td>
                            <td>{{ $c->telephone }}</td>
                            <td>{{ $c->created_at }}</td>
                            <td>
                                <div class="icon-button-demo">
                                    <a href="{{ route('casual_clients.show', $c->id) }}">
                                        <button class="btn btn-info waves-effect" type="button">
                                            <i class="material-icons">zoom_in</i>
                                        </button>
                                    </a>

                                    <a href="{{ route('casual_clients.edit', $c->id) }}">
                                        <button class="btn btn-warning waves-effect" type="button">
                                            <i class="material-icons">border_color</i>
                                        </button>
                                    </a>

                                    <button class="btn btn-danger waves-effect btn-delete" type="button" title="Cancelar Orden">
                                            <i class="material-icons">delete_forever</i>
                                        </button>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{ $clients->appends(['date_start' => $date_start, 'q' => $q, 'date_end' => $date_end, 'description' => $description])->links()
                }}
            </div>
        </div>
    </div>
</div>
{!! Form::open(['route' => ['casual_clients.destroy',':ROW_ID'], 'method' => 'DELETE',
'id' => 'form-delete']) !!}
<!-- #END# Basic Table -->
@endsection
 
@section('css')
<!-- Bootstrap Material Datetime Picker Css -->
<link href="{{ '/admin/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css' }}" rel="stylesheet"
/>

<!-- Wait Me Css -->
<link href="{{ '/admin/plugins/waitme/waitMe.css' }}" rel="stylesheet" />

<!-- Bootstrap Select Css -->
<link href="{{ '/admin/plugins/bootstrap-select/css/bootstrap-select.css' }}" rel="stylesheet" />
@endsection
 
@section('js')
<!-- Sweetalert Css -->
<link href="{{ '/admin/plugins/sweetalert/sweetalert.css' }}" rel="stylesheet" />
<!-- Moment Plugin Js -->
<script src="{{ '/admin/plugins/momentjs/moment.js' }}"></script>
<!-- Bootstrap Material Datetime Picker Plugin Js -->
<script src="{{ '/admin/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js' }}"></script>

<script src="{{ '/admin/js/pages/forms/basic-form-elements.js' }}"></script>

<script src="{{ '/admin/plugins/sweetalert/sweetalert.min.js' }}"></script>
@include('administration.templates.partials.delete_row')

@endsection

resources/views/administration/clients/view.blade.php
@extends('administration.templates.layout') 
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Cliente Casual
                    <small>Nro: {{ $client->id}}</small>
                </h2>
            </div>
            <div class="body">
                <div class="row">
                    <div class="col-md-2">
                        <p>
                            <b>Fecha de Alta</b>
                        </p>
                        <p>{{ $client->created_at->format('Y-m-d') }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Descripción:</b>
                        </p>
                        <p>{{$client->description }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Cedula:</b>
                        </p>
                        <p>{{ $client->idnum }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Ruc:</b>
                        </p>
                        <p>{{$client->tax_name }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Razon Social:</b>
                        </p>
                        <p>{{$client->tax_code }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Telefono:</b>
                        </p>
                        <p>{{$client->telephone }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Fecha de Nacimiento:</b>
                        </p>
                        <p>{{$client->birthday }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Dirección:</b>
                        </p>
                        <p>{{$client->addresses[0]->address }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Dirección:</b>
                        </p>
                        <p>{{$client->addresses[0]->address2 }}</p>
                    </div>
                    <div class="col-md-2">
                        <p>
                            <b>Ciudad:</b>
                        </p>
                        <p>{{$client->addresses[0]->cities->description }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    Compras
                </h2>
            </div>
            <div class="body table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Fecha de Compra</th>
                            <th>Estado</th>
                            <th>Monto</th>
                            <th>Forma de Pago</th>
                            <th>Aex</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($client->purchases as $s)
                        <tr>
                            <th>{{ $s->id }}</th>
                            <th>{{ $s->purchase_date }}</th>
                            <th>{{ $s->statuses->description }}</th>
                            <th>{{ number_format($s->order_amount, 0, ',', '.') }}</th>
                            <th>{{ $s->paymentForm->description}}</th>
                            <th>{{ $s->aex_tracking_id }}</th>
                            <th>
                                <div class="icon-button-demo">
                                    <a href="{{ route('sales.show', $s->id) }}">
                                <button class="btn btn-info waves-effect" type="button">
                                    <i class="material-icons">zoom_in</i>
                                </button>
                            </a>
                                </div>
                            </th>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection